INSERT INTO course VALUES (1, 'Progressive demand-driven process improvement', 'Centralized coherent adapter', 3);
INSERT INTO course VALUES (2, 'Vision-oriented high-level success', 'Vision-oriented 4thgeneration hierarchy', 4);
INSERT INTO course VALUES (3, 'Proactive mission-critical challenge', 'Right-sized non-volatile structure', 1);
INSERT INTO course VALUES (4, 'Distributed asymmetric knowledge user', 'Universal incremental Graphical User Interface', 2);
INSERT INTO course VALUES (5, 'Compatible heuristic moderator', 'Quality-focused mission-critical Local Area Network', 4);
INSERT INTO course VALUES (6, 'Progressive web-enabled projection', 'Up-sized leadingedge synergy', 1);
INSERT INTO course VALUES (7, 'Configurable radical intranet', 'Programmable mobile data-warehouse', 1);
INSERT INTO course VALUES (8, 'Proactive executive frame', 'Centralized high-level workforce', 4);
INSERT INTO course VALUES (9, 'Distributed 4thgeneration firmware', 'Balanced upward-trending methodology', 2);
INSERT INTO course VALUES (10, 'Ameliorated motivating matrix', 'Team-oriented user-facing infrastructure', 1);
INSERT INTO course VALUES (11, 'Distributed foreground structure', 'Down-sized bottom-line strategy', 2);
INSERT INTO course VALUES (12, 'Face-to-face scalable utilization', 'Balanced asymmetric function', 2);
INSERT INTO course VALUES (13, 'Business-focused 24/7 approach', 'Universal incremental customer loyalty', 1);
INSERT INTO course VALUES (14, 'Grass-roots system-worthy support', 'Versatile cohesive secured line', 2);
INSERT INTO course VALUES (15, 'User-friendly contextually-based database', 'Distributed bottom-line instruction set', 3);
INSERT INTO course VALUES (16, 'Seamless context-sensitive capability', 'Customer-focused modular toolset', 1);
INSERT INTO course VALUES (17, 'Balanced grid-enabled array', 'Synergized upward-trending matrix', 4);
INSERT INTO course VALUES (18, 'Phased system-worthy benchmark', 'Cross-group non-volatile strategy', 2);
INSERT INTO course VALUES (19, 'Enterprise-wide solution-oriented open system', 'Robust reciprocal interface', 1);
INSERT INTO course VALUES (20, 'Progressive demand-driven process improvement', 'Mandatory uniform approach', 1);
INSERT INTO course VALUES (21, 'Diverse modular pricing structure', 'Up-sized content-based methodology', 3);
INSERT INTO course VALUES (22, 'Synergistic human-resource instruction set', 'Synergistic intangible Graphic Interface', 3);
INSERT INTO course VALUES (23, 'Ameliorated methodical open architecture', 'Organic coherent challenge', 2);
INSERT INTO course VALUES (24, 'Pre-emptive client-driven adapter', 'Multi-channeled bi-directional intranet', 4);
INSERT INTO course VALUES (25, 'Integrated foreground access', 'Total solution-oriented matrix', 4);
INSERT INTO course VALUES (26, 'Adaptive uniform moderator', 'Inverse contextually-based task-force', 3);
INSERT INTO course VALUES (27, 'Centralized analyzing support', 'Centralized multi-tasking functionalities', 4);
INSERT INTO course VALUES (28, 'Total 24hour software', 'Adaptive explicit paradigm', 4);
INSERT INTO course VALUES (29, 'Expanded multi-tasking project', 'Cross-platform dedicated success', 4);
INSERT INTO course VALUES (30, 'Sharable neutral contingency', 'Extended neutral contingency', 1);
INSERT INTO course VALUES (31, 'Reactive didactic synergy', 'Expanded well-modulated throughput', 4);
INSERT INTO course VALUES (32, 'Total 24hour software', 'Sharable cohesive concept', 3);
INSERT INTO course VALUES (33, 'Decentralized modular hardware', 'Optional 6thgeneration productivity', 3);
INSERT INTO course VALUES (34, 'Grass-roots non-volatile strategy', 'Face-to-face encompassing benchmark', 2);
INSERT INTO course VALUES (35, 'Automated background Local Area Network', 'Fundamental responsive toolset', 3);
INSERT INTO course VALUES (36, 'Balanced optimal extranet', 'Down-sized mobile infrastructure', 4);
INSERT INTO course VALUES (37, 'Switchable mobile open architecture', 'Synergized content-based alliance', 4);
INSERT INTO course VALUES (38, 'Automated background Local Area Network', 'Multi-channeled 5thgeneration approach', 3);
INSERT INTO course VALUES (39, 'Total 24hour software', 'Triple-buffered global productivity', 4);
INSERT INTO course VALUES (40, 'Function-based human-resource alliance', 'Fully-configurable tangible moratorium', 2);
INSERT INTO course VALUES (41, 'Synergistic human-resource instruction set', 'Reverse-engineered needs-based knowledge user', 2);
INSERT INTO course VALUES (42, 'Compatible heuristic moderator', 'Multi-channeled needs-based functionalities', 3);
INSERT INTO course VALUES (43, 'Open-source analyzing info-mediaries', 'Fully-configurable disintermediate conglomeration', 3);
INSERT INTO course VALUES (44, 'User-friendly disintermediate synergy', 'Centralized global hardware', 4);
INSERT INTO course VALUES (45, 'Operative system-worthy forecast', 'Decentralized upward-trending project', 3);
INSERT INTO course VALUES (46, 'Reactive didactic synergy', 'Programmable systematic concept', 1);
INSERT INTO course VALUES (47, 'User-centric 3rdgeneration paradigm', 'Cloned encompassing productivity', 1);
INSERT INTO course VALUES (48, 'Integrated static collaboration', 'Open-source demand-driven info-mediaries', 2);
INSERT INTO course VALUES (49, 'Distributed foreground structure', 'Cloned content-based frame', 3);
INSERT INTO course VALUES (50, 'Distributed global application', 'Enhanced tertiary pricing structure', 3);
INSERT INTO course VALUES (51, 'Decentralized modular hardware', 'Stand-alone systematic utilization', 2);
INSERT INTO course VALUES (52, 'Robust grid-enabled workforce', 'Quality-focused high-level methodology', 4);
INSERT INTO course VALUES (53, 'Reactive didactic synergy', 'Organic optimizing Local Area Network', 1);
INSERT INTO course VALUES (54, 'Integrated foreground access', 'Reduced fresh-thinking initiative', 3);
INSERT INTO course VALUES (55, 'Seamless context-sensitive capability', 'Persistent zero administration analyzer', 1);
INSERT INTO course VALUES (56, 'Reactive didactic synergy', 'Visionary systemic database', 4);
INSERT INTO course VALUES (57, 'Progressive demand-driven process improvement', 'Function-based transitional encryption', 3);
INSERT INTO course VALUES (58, 'Robust grid-enabled workforce', 'Horizontal value-added flexibility', 3);
INSERT INTO course VALUES (59, 'Grass-roots non-volatile strategy', 'Public-key tangible ability', 4);
INSERT INTO course VALUES (60, 'Optimized exuding focus group', 'Compatible encompassing Graphic Interface', 3);
INSERT INTO course VALUES (61, 'Up-sized asymmetric knowledgebase', 'Right-sized 5thgeneration benchmark', 2);
INSERT INTO course VALUES (62, 'Function-based human-resource alliance', 'Profound empowering projection', 4);
INSERT INTO course VALUES (63, 'Exclusive foreground challenge', 'Pre-emptive systematic instruction set', 4);
INSERT INTO course VALUES (64, 'Progressive web-enabled projection', 'Distributed coherent focus group', 4);
INSERT INTO course VALUES (65, 'Balanced grid-enabled array', 'Self-enabling incremental contingency', 1);
INSERT INTO course VALUES (66, 'Automated background Local Area Network', 'Digitized national Graphical User Interface', 4);
INSERT INTO course VALUES (67, 'Enterprise-wide solution-oriented open system', 'Devolved 6thgeneration collaboration', 1);
INSERT INTO course VALUES (68, 'Compatible heuristic moderator', 'Ameliorated disintermediate benchmark', 2);
INSERT INTO course VALUES (69, 'Business-focused intangible middleware', 'Enterprise-wide full-range time-frame', 3);
INSERT INTO course VALUES (70, 'Pre-emptive optimal complexity', 'Advanced even-keeled extranet', 3);
INSERT INTO course VALUES (71, 'Up-sized didactic secured line', 'Robust motivating architecture', 1);
INSERT INTO course VALUES (72, 'Stand-alone discrete frame', 'Ergonomic modular portal', 1);
INSERT INTO course VALUES (73, 'Inverse needs-based function', 'Open-source empowering parallelism', 1);
INSERT INTO course VALUES (74, 'Configurable radical intranet', 'Stand-alone actuating initiative', 3);
INSERT INTO course VALUES (75, 'Multi-lateral multimedia portal', 'Compatible 24hour capability', 4);
INSERT INTO course VALUES (76, 'Up-sized static pricing structure', 'Multi-tiered solution-oriented analyzer', 3);
INSERT INTO course VALUES (77, 'Operative system-worthy forecast', 'Adaptive asynchronous intranet', 2);
INSERT INTO course VALUES (78, 'Function-based human-resource alliance', 'Self-enabling executive policy', 3);
INSERT INTO course VALUES (79, 'Stand-alone discrete frame', 'Networked bottom-line concept', 4);
INSERT INTO course VALUES (80, 'Vision-oriented high-level success', 'Compatible optimal ability', 1);
INSERT INTO course VALUES (81, 'Mandatory responsive methodology', 'Devolved disintermediate adapter', 3);
INSERT INTO course VALUES (82, 'Automated background Local Area Network', 'Profit-focused stable projection', 3);
INSERT INTO course VALUES (83, 'Distributed foreground structure', 'Object-based contextually-based extranet', 1);
INSERT INTO course VALUES (84, 'Vision-oriented high-level success', 'Horizontal responsive function', 2);
INSERT INTO course VALUES (85, 'Robust contextually-based frame', 'Polarized 24/7 protocol', 3);
INSERT INTO course VALUES (86, 'Enterprise-wide systemic protocol', 'Configurable heuristic projection', 3);
INSERT INTO course VALUES (87, 'Mandatory bifurcated Internet solution', 'Customizable regional model', 3);
INSERT INTO course VALUES (88, 'Enterprise-wide solution-oriented open system', 'User-centric holistic data-warehouse', 2);
INSERT INTO course VALUES (89, 'Pre-emptive optimal complexity', 'Implemented homogeneous emulation', 1);
INSERT INTO course VALUES (90, 'Progressive demand-driven process improvement', 'Down-sized global instruction set', 4);
INSERT INTO course VALUES (91, 'Assimilated next generation pricing structure', 'Phased executive middleware', 2);
INSERT INTO course VALUES (92, 'Advanced systemic initiative', 'Future-proofed impactful standardization', 4);
INSERT INTO course VALUES (93, 'Advanced systemic initiative', 'Programmable secondary task-force', 3);
INSERT INTO course VALUES (94, 'Optimized exuding focus group', 'User-friendly impactful task-force', 3);
INSERT INTO course VALUES (95, 'Seamless context-sensitive capability', 'Adaptive incremental interface', 3);
INSERT INTO course VALUES (96, 'Distributed foreground structure', 'Multi-channeled 4thgeneration product', 3);
INSERT INTO course VALUES (97, 'Expanded multi-tasking project', 'Object-based hybrid process improvement', 4);
INSERT INTO course VALUES (98, 'Compatible heuristic moderator', 'De-engineered zero tolerance orchestration', 4);
INSERT INTO course VALUES (99, 'User-friendly contextually-based database', 'Profound radical help-desk', 4);
INSERT INTO course VALUES (100, 'Total 24hour software', 'Configurable high-level encoding', 3);
