INSERT INTO student VALUES (1821, 'Michael Lopez', 'Phased responsive help-desk', 135);
INSERT INTO student VALUES (1525, 'Christina King', 'Digitized context-sensitive emulation', 32);
INSERT INTO student VALUES (1155, 'Tiffany Roberts', 'Virtual mission-critical projection', 47);
INSERT INTO student VALUES (1366, 'Joshua Walsh', 'Function-based human-resource alliance', 63);
INSERT INTO student VALUES (1096, 'Linda Glover', 'Virtual mission-critical projection', 43);
INSERT INTO student VALUES (1288, 'Cheryl Walker', 'Future-proofed impactful product', 87);
INSERT INTO student VALUES (1005, 'Derrick Bailey', 'Visionary modular Graphic Interface', 37);
INSERT INTO student VALUES (1666, 'Angie Lindsey', 'Mandatory responsive methodology', 81);
INSERT INTO student VALUES (1130, 'James Davis', 'Robust grid-enabled workforce', 111);
INSERT INTO student VALUES (1870, 'Kimberly Kim', 'Progressive demand-driven process improvement', 27);
INSERT INTO student VALUES (1437, 'David Gonzalez', 'Integrated static collaboration', 128);
INSERT INTO student VALUES (1935, 'Kimberly Barnes', 'Organized bi-directional adapter', 99);
INSERT INTO student VALUES (1058, 'Jennifer Reed', 'Public-key web-enabled strategy', 80);
INSERT INTO student VALUES (1666, 'Rachel Johnson', 'De-engineered coherent structure', 51);
INSERT INTO student VALUES (1662, 'Timothy Lara', 'Proactive executive frame', 11);
INSERT INTO student VALUES (1537, 'Kristin Stewart', 'Balanced optimal extranet', 129);
INSERT INTO student VALUES (1925, 'Haley Ruiz', 'Versatile tangible benchmark', 13);
INSERT INTO student VALUES (1525, 'David Mitchell', 'Cloned clear-thinking frame', 5);
INSERT INTO student VALUES (1284, 'Sara Olson', 'Up-sized bi-directional function', 139);
INSERT INTO student VALUES (1542, 'Jessica Villanueva', 'Centralized analyzing support', 91);
INSERT INTO student VALUES (1031, 'Ann Pierce', 'Grass-roots system-worthy support', 5);
INSERT INTO student VALUES (1887, 'Scott Jones', 'Balanced grid-enabled array', 7);
INSERT INTO student VALUES (1364, 'Gregory Hansen', 'Optimized exuding focus group', 102);
INSERT INTO student VALUES (1251, 'David Roman', 'Operative high-level Graphic Interface', 97);
INSERT INTO student VALUES (1496, 'Sheri Weaver', 'Adaptive uniform moderator', 1);
INSERT INTO student VALUES (1536, 'Theresa Benjamin', 'Total 24hour software', 10);
INSERT INTO student VALUES (1677, 'John Bell', 'Stand-alone discrete frame', 4);
INSERT INTO student VALUES (1345, 'Sarah Parrish', 'Operative high-level Graphic Interface', 45);
INSERT INTO student VALUES (1900, 'Matthew Smith', 'Synergized global benchmark', 45);
INSERT INTO student VALUES (1732, 'Aaron Cooley', 'Multi-lateral multimedia portal', 109);
INSERT INTO student VALUES (1920, 'Earl Sanchez', 'Face-to-face scalable utilization', 120);
INSERT INTO student VALUES (1347, 'Daniel Krause', 'Distributed global application', 88);
INSERT INTO student VALUES (1832, 'Andrea Buchanan', 'Configurable reciprocal data-warehouse', 73);
INSERT INTO student VALUES (1965, 'Jacqueline Jensen', 'Open-source analyzing info-mediaries', 94);
INSERT INTO student VALUES (1326, 'Dawn Thompson', 'Pre-emptive optimal complexity', 147);
INSERT INTO student VALUES (1912, 'Stephanie Rivera', 'Secured mission-critical open system', 144);
INSERT INTO student VALUES (1118, 'Morgan Walker', 'Vision-oriented high-level success', 146);
INSERT INTO student VALUES (1945, 'Mr. Antonio Jackson', 'Configurable reciprocal data-warehouse', 48);
INSERT INTO student VALUES (1342, 'Justin Brooks', 'Future-proofed impactful product', 51);
INSERT INTO student VALUES (1068, 'Dennis Davis', 'Expanded multi-tasking project', 132);
INSERT INTO student VALUES (1879, 'Kathy Peterson', 'Distributed 4thgeneration firmware', 122);
INSERT INTO student VALUES (1220, 'Sarah Weaver', 'Visionary modular Graphic Interface', 149);
INSERT INTO student VALUES (1646, 'Dylan Wagner', 'Balanced optimal extranet', 36);
INSERT INTO student VALUES (1418, 'Jamie Adams', 'Assimilated next generation pricing structure', 91);
INSERT INTO student VALUES (1563, 'Kevin Zimmerman', 'Pre-emptive optimal complexity', 136);
INSERT INTO student VALUES (1148, 'Sara Miller', 'Secured mission-critical open system', 77);
INSERT INTO student VALUES (1075, 'Perry Mason', 'Versatile tangible benchmark', 42);
INSERT INTO student VALUES (1928, 'Jonathan Miles', 'Enterprise-wide multimedia secured line', 102);
INSERT INTO student VALUES (1202, 'Andrew Ochoa', 'Compatible executive definition', 33);
INSERT INTO student VALUES (1804, 'Karen Parker', 'Up-sized static pricing structure', 71);
INSERT INTO student VALUES (1585, 'Elizabeth Murphy', 'Function-based human-resource alliance', 60);
INSERT INTO student VALUES (1777, 'Nicholas Hall', 'Cloned clear-thinking frame', 108);
INSERT INTO student VALUES (1676, 'Jennifer Davis', 'Synergistic tertiary workforce', 31);
INSERT INTO student VALUES (1662, 'Julia Lopez', 'Horizontal scalable migration', 117);
INSERT INTO student VALUES (1206, 'Matthew Anderson', 'Open-source analyzing info-mediaries', 102);
INSERT INTO student VALUES (1354, 'Charles Alvarado', 'Cloned clear-thinking frame', 86);
INSERT INTO student VALUES (1380, 'Lydia Bullock', 'Enterprise-wide systemic protocol', 5);
INSERT INTO student VALUES (1181, 'Christopher Smith', 'Distributed foreground structure', 38);
INSERT INTO student VALUES (1886, 'Mrs. Heather Kim', 'Reactive didactic synergy', 66);
INSERT INTO student VALUES (1123, 'Christine Jensen', 'Operative high-level Graphic Interface', 5);
INSERT INTO student VALUES (1006, 'Adriana Brown', 'Centralized analyzing support', 9);
INSERT INTO student VALUES (1426, 'Kathy Brown', 'User-friendly contextually-based database', 58);
INSERT INTO student VALUES (1341, 'Debra Garcia', 'Virtual mission-critical projection', 51);
INSERT INTO student VALUES (1461, 'Sherry Douglas', 'Virtual mission-critical projection', 23);
INSERT INTO student VALUES (1828, 'Jose Murphy', 'Enterprise-wide systemic protocol', 16);
INSERT INTO student VALUES (1567, 'Michael Acosta', 'Configurable reciprocal data-warehouse', 0);
INSERT INTO student VALUES (1565, 'Laura Smith', 'Up-sized static pricing structure', 146);
INSERT INTO student VALUES (1656, 'Jennifer Hicks', 'Total 24hour software', 90);
INSERT INTO student VALUES (1751, 'Stephanie Garcia', 'Optimized exuding focus group', 118);
INSERT INTO student VALUES (1169, 'Heather Davis', 'Open-source analyzing info-mediaries', 105);
INSERT INTO student VALUES (1467, 'Jessica Smith', 'Synergistic asynchronous flexibility', 62);
INSERT INTO student VALUES (1859, 'Willie Chen', 'User-centric 3rdgeneration paradigm', 66);
INSERT INTO student VALUES (1687, 'Sandra Rowland', 'Phased system-worthy benchmark', 99);
INSERT INTO student VALUES (1881, 'Mr. Samuel Martin MD', 'Progressive web-enabled projection', 41);
INSERT INTO student VALUES (1685, 'Michelle Clayton', 'Expanded multi-tasking project', 20);
INSERT INTO student VALUES (1442, 'Seth Washington Jr.', 'Operative high-level Graphic Interface', 131);
INSERT INTO student VALUES (1339, 'Monica Adams', 'Digitized user-facing infrastructure', 36);
INSERT INTO student VALUES (1706, 'William Fields', 'Decentralized modular hardware', 90);
INSERT INTO student VALUES (1071, 'Eric Mitchell', 'User-friendly disintermediate synergy', 91);
INSERT INTO student VALUES (1192, 'Sharon Wilson', 'Reactive next generation extranet', 71);
INSERT INTO student VALUES (1804, 'Christopher Adams', 'Synergistic tertiary workforce', 9);
INSERT INTO student VALUES (1921, 'Pamela Coleman', 'Self-enabling heuristic forecast', 70);
INSERT INTO student VALUES (1393, 'Jack Burns', 'Synchronized global emulation', 116);
INSERT INTO student VALUES (1246, 'Catherine Cook', 'Reverse-engineered static encryption', 11);
INSERT INTO student VALUES (1126, 'Cynthia Lam', 'Centralized eco-centric product', 70);
INSERT INTO student VALUES (1492, 'Gregg Hampton', 'Enhanced client-server infrastructure', 91);
INSERT INTO student VALUES (1797, 'Benjamin Harrison', 'Business-focused intangible middleware', 15);
INSERT INTO student VALUES (1252, 'Rhonda Ochoa', 'Organized bi-directional adapter', 21);
INSERT INTO student VALUES (1472, 'Luis Huffman', 'Reverse-engineered systematic implementation', 93);
INSERT INTO student VALUES (1224, 'Jennifer Williams', 'Ameliorated methodical open architecture', 137);
INSERT INTO student VALUES (1396, 'Marcus Leonard', 'Enterprise-wide solution-oriented open system', 46);
INSERT INTO student VALUES (1335, 'Rebecca Lyons', 'Digitized context-sensitive emulation', 113);
INSERT INTO student VALUES (1561, 'Madison Murillo', 'Digitized user-facing infrastructure', 15);
INSERT INTO student VALUES (1268, 'Dylan Jackson', 'Proactive mission-critical challenge', 31);
INSERT INTO student VALUES (1280, 'John Rodriguez', 'Seamless context-sensitive capability', 104);
INSERT INTO student VALUES (1985, 'Michelle Perez', 'Up-sized static pricing structure', 76);
INSERT INTO student VALUES (1950, 'Elizabeth Wilson', 'Switchable mobile open architecture', 55);
INSERT INTO student VALUES (1475, 'Marcus Klein', 'Multi-layered secondary knowledgebase', 38);
INSERT INTO student VALUES (1266, 'Elizabeth Barton', 'Robust grid-enabled workforce', 88);
INSERT INTO student VALUES (1440, 'Brian Richardson', 'Multi-channeled methodical definition', 8);
